[".config/tmux/plugins/smart-splits"]
   type = "git-repo"
    url = "https://github.com/mrjones2014/smart-splits.nvim.git"
    refreshPeriod = "168h"
[".config/tmux/plugins/catppuccin/tmux"]
    type = "git-repo"
    url = "https://github.com/catppuccin/tmux.git"
    refreshPeriod = "168h"
[".config/tmux/plugins/tmux-plugins/tmux-cpu"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tmux-cpu.git"
    refreshPeriod = "168h"
[".config/tmux/plugins/tmux-plugins/tmux-battery"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tmux-battery.git"
    refreshPeriod = "168h"
[".config/tmux/plugins/tmux-plugins/tmux-fzf"]
    type = "git-repo"
    url = "https://github.com/sainnhe/tmux-fzf.git"
    refreshPeriod = "168h"
