[tools]
# CLI tools
ghq = "latest"
jq = "latest"
fzf = "latest"
lazygit = "latest"
delta = "latest" # diff の表示を見やすくしてくれるツール
rg = "latest"
coreutils = "latest" # macOSは､BSD版なので､GNU版のほうが使い慣れているため｡
gh = "latest" # GitHub CLI
awscli = "latest"
gcloud = "latest"

# For Go
go = "latest"

# For Node.js
node = "latest"
"npm:@github/copilot" = "latest"

# For Rust
rust = "latest"

# For Lua
"cargo:selene" = "latest"

# For Python
python = "latest"
uv = "latest"
poetry = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
