[tools]
# CLI tools
ghq = "latest"
jq = "latest"
fzf = "latest"
lazygit = "latest"
delta = "latest" # diff の表示を見やすくしてくれるツール
rg = "latest"
coreutils = "latest" # macOSは､BSD版なので､GNU版のほうが使い慣れているため｡
gh = "latest" # GitHub CLI
awscli = "latest"
gcloud = "latest"

# For Go
go = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = { version = "latest" }


# For Node.js
node = "latest"
"npm:@github/copilot" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@zed-industries/claude-code-acp" = "latest"
"npm:ccusage" = "latest"
"npm:tree-sitter-cli" = "latest"

# For Rust
rust = "latest"

# For Lua
"cargo:selene" = "latest"

# For Python
python = "latest"
uv = "latest"
poetry = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
